# Generated by Django 4.2.28 on 2026-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ejecutivo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('filas_procesadas', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
