# Generated by Django 4.2.28 on 2026-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_importhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rut',
            new_name='rut_empresa',
        ),
        migrations.RenameField(
            model_name='coordinador',
            old_name='rut',
            new_name='rut_coordinador',
        ),
        migrations.RenameField(
            model_name='ejecutivo',
            old_name='rut',
            new_name='rut_ejecutivo',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='rut',
            new_name='rut_proveedor',
        ),
    ]
