# Generated by Django 4.2.28 on 2026-02-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cliente_email_remove_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], max_length=20),
        ),
    ]
