# Generated by Django 4.2.28 on 2026-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contrato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecutivo',
            name='area_departamento',
            field=models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('marketing', 'Marketing'), ('operaciones', 'Operaciones'), ('finanzas', 'Finanzas'), ('rrhh', 'Recursos Humanos'), ('ti', 'Tecnología e Informática'), ('administracion', 'Administración'), ('comercial', 'Comercial'), ('logistica', 'Logística'), ('atencion_cliente', 'Atención al Cliente'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
