# Generated by Django 4.2.28 on 2026-02-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ejecutivo_area_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='fecha_proxima_accion',
            new_name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='tipo_seguimiento',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='accion',
            field=models.CharField(default='Sin Acción', max_length=50),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha_respuesta_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='respuesta_seguimiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='tipo',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
