# Generated by Django 4.2.28 on 2026-02-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cliente_email_cliente_nombre_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
    ]
