# Generated by Django 4.2.28 on 2026-02-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_cliente_email_remove_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_principal_de', to='api.coordinador'),
        ),
    ]
