# Generated by Django 4.2.28 on 2026-02-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cliente_contacto_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ejecutivo'),
        ),
    ]
