# Generated by Django 4.2.28 on 2026-02-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_coordinador_ejecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantidad_sucursales',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_colaboradores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_empresarial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_convenio',
            field=models.CharField(choices=[('otech', 'OTEC'), ('sence', 'SENCE'), ('particular', 'Particular')], default='particular', max_length=20),
        ),
        migrations.AddField(
            model_name='coordinador',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
