# Generated by Django 4.2.28 on 2026-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
