# Generated by Django 4.2.28 on 2026-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cliente_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinador',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ejecutivo',
            name='area_departamento',
        ),
        migrations.RemoveField(
            model_name='ejecutivo',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='ejecutivo',
            name='region',
        ),
        migrations.AddField(
            model_name='coordinador',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejecutivo',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('marketing', 'Marketing'), ('operaciones', 'Operaciones'), ('finanzas', 'Finanzas'), ('rrhh', 'Recursos Humanos'), ('ti', 'Tecnología e Informática'), ('administracion', 'Administración'), ('comercial', 'Comercial'), ('logistica', 'Logística'), ('atencion_cliente', 'Atención al Cliente'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
