# Generated by Django 4.2.28 on 2026-02-23 23:03

import backend.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_coordinador_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='api.proveedor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_empresarial',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[backend.api.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[backend.api.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='ejecutivo',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[backend.api.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[backend.api.models.validate_phone]),
        ),
        migrations.DeleteModel(
            name='ContratoServicio',
        ),
    ]
