# Generated by Django 4.2.28 on 2026-02-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_servicio_proveedores_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='proveedores',
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='api.proveedor'),
        ),
    ]
