# Generated by Django 4.2.28 on 2026-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_servicio_proveedor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
