# Generated by Django 4.2.28 on 2026-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_contrato_creado_por_contrato_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='api.proveedor'),
        ),
    ]
