# Generated by Django 4.2.28 on 2026-02-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_contrato_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='updated_at',
        ),
    ]
