# Generated by Django 4.2.28 on 2026-02-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_contrato_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_registro',
            field=models.CharField(choices=[('Contrato', 'Contrato'), ('Propuesta', 'Propuesta')], default='Contrato', max_length=20),
        ),
    ]
