# Generated by Django 4.2.28 on 2026-02-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_contrato_tipo_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_emision',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_recepcion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_vencimiento',
        ),
    ]
