# Generated by Django 4.2.28 on 2026-02-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_fecha_emision_contrato_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='api.contrato'),
        ),
    ]
