# Generated by Django 4.2.28 on 2026-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_seguimiento_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
