# Generated by Django 4.2.28 on 2026-02-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_contrato_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejecutivo',
            old_name='departamento',
            new_name='area_departamento',
        ),
    ]
