# Generated by Django 4.2.28 on 2026-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_departamento_ejecutivo_area_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_empresa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_otic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_convenio',
            field=models.CharField(choices=[('otic', 'OTIC'), ('sence', 'SENCE'), ('particular', 'Particular')], default='particular', max_length=20),
        ),
    ]
