# Generated by Django 4.2.28 on 2026-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_manual_financial_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_convenio',
            field=models.CharField(choices=[('OTIC', 'OTIC'), ('SENCE', 'SENCE'), ('Particular', 'Particular')], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cerrado', 'Cerrado'), ('Finalizado', 'Finalizado')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ejecutivo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10),
        ),
    ]
