# Generated by Django 4.2.28 on 2026-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_cliente_estado_alter_cliente_tipo_convenio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='proveedor',
        ),
    ]
