# Generated by Django 4.2.28 on 2026-02-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_servicio_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='a_pagar_empresa',
            new_name='pago_empresa',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='a_pagar_otic',
            new_name='pago_otic',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_general',
            new_name='valor_persona',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_registro',
        ),
        migrations.AddField(
            model_name='contrato',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_convenio',
            field=models.CharField(blank=True, choices=[('OTIC', 'OTIC'), ('SENCE', 'SENCE'), ('Particular', 'Particular')], default='Particular', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('nuevo requerimiento', 'Nuevo Requerimiento'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en proceso', 'En Proceso'), ('liquidado', 'Liquidado'), ('finalizado', 'Finalizado')], default='nuevo requerimiento', max_length=30),
        ),
    ]
