# Generated by Django 4.2.28 on 2026-02-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_a_pagar_empresa_contrato_pago_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='proveedores',
        ),
    ]
