# Generated by Django 4.2.28 on 2026-02-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_contrato_proveedores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='rubro',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='pago_empresa',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='pago_otic',
        ),
    ]
