# Generated by Django 4.2.28 on 2026-02-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_rubro_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='valor_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='curso',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ejecutivo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ejecutivo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
