# Generated by Django 4.2.28 on 2026-02-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_curso_valor_persona_curso_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='coordinador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.coordinador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ejecutivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ejecutivo'),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ejecutivo'),
        ),
    ]
