# Generated by Django 4.2.28 on 2026-02-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_contrato_coordinador_alter_contrato_ejecutivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='valor_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicio',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coordinador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ejecutivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ejecutivo'),
        ),
    ]
