# Generated by Django 4.2.28 on 2026-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_cliente_nombre_alter_cliente_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('nuevo requerimiento', 'Nuevo Requerimiento'), ('aprobado', 'Aprobado'), ('en firma', 'En Firma'), ('rechazado', 'Rechazado'), ('en proceso', 'En Proceso'), ('liquidado', 'Liquidado'), ('finalizado', 'Finalizado')], default='nuevo requerimiento', max_length=30),
        ),
    ]
